void info(void);
void ajuda(void);
void clear(void);
void inventario(void);
void ir(char *substantivo);
void olhar(char *substantivo);
void pegar(char *substantivo);
void largar(char *subsantivo);
void rank(char *substantivo);
void atacar(char *substantivo);
void finalizar_borda_status(int str_len, int n);
void status(void);
void usar(char *substantivo);
void salvar();
void load();
